#[derive(Debug, PartialEq)]
pub enum Terminal {
    Int,
    Float,
    If,
    Else,
    While,
    Return,
    Print,
    Id,
    Num,
    Assign,
    Plus,
    Minus,
    Multiply,
    Divide,
    Equals,
    NotEquals,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    StartParen,
    EndParen,
    StartBrace,
    EndBrace,
    Comma,
    Semicolon,
    Eof,
    Error,
}
impl Terminal {
    pub fn to_code(&self) -> u8 {
        match self {
            Terminal::Int => 1,
            Terminal::Float => 2,
            Terminal::If => 3,
            Terminal::Else => 4,
            Terminal::While => 5,
            Terminal::Return => 6,
            Terminal::Print => 7,
            Terminal::Id => 8,
            Terminal::Num => 9,
            Terminal::Assign => 10,
            Terminal::Plus => 11,
            Terminal::Minus => 12,
            Terminal::Multiply => 13,
            Terminal::Divide => 14,
            Terminal::Equals => 15,
            Terminal::NotEquals => 16,
            Terminal::LessThan => 17,
            Terminal::GreaterThan => 18,
            Terminal::LessThanOrEqual => 19,
            Terminal::GreaterThanOrEqual => 20,
            Terminal::StartParen => 21,
            Terminal::EndParen => 22,
            Terminal::StartBrace => 23,
            Terminal::EndBrace => 24,
            Terminal::Comma => 25,
            Terminal::Semicolon => 26,
            Terminal::Eof => 27,
            Terminal::Error => 28,
        }
    }

    pub fn keyword_to_terminal(keyword: &str) -> Option<Terminal> {
        match keyword {
            "int" => Some(Terminal::Int),
            "float" => Some(Terminal::Float),
            "if" => Some(Terminal::If),
            "else" => Some(Terminal::Else),
            "while" => Some(Terminal::While),
            "return" => Some(Terminal::Return),
            "print" => Some(Terminal::Print),
            _ => None,
        }
    }
}

#[derive(Debug, PartialEq)]
pub enum NonTerminal {
    Program,
    FunctionList,
    FunctionListPrime,
    Function,
    ParamListOpt,
    ParamList,
    ParamListPrime,
    Param,
    Block,
    DeclListOpt,
    DeclList,
    DeclListPrime,
    VarDecl,
    StmtListOpt,
    StmtList,
    StmtListPrime,
    Stmt,
    AssignStmt,
    ReturnStmt,
    PrintStmt,
    IfStmt,
    ElsePart,
    WhileStmt,
    Expr,
    RelExpr,
    RelExprPrime,
    RelOp,
    AddExpr,
    AddExprPrime,
    MulExpr,
    MulExprPrime,
    Factor,
    FactorTail,
    ArgListOpt,
    ArgList,
    ArgListPrime,
    Type,
}
impl NonTerminal {
    pub fn to_code(&self) -> u8 {
        match self {
            NonTerminal::Program => 29,
            NonTerminal::FunctionList => 30,
            NonTerminal::FunctionListPrime => 31,
            NonTerminal::Function => 32,
            NonTerminal::ParamListOpt => 33,
            NonTerminal::ParamList => 34,
            NonTerminal::ParamListPrime => 35,
            NonTerminal::Param => 36,
            NonTerminal::Block => 37,
            NonTerminal::DeclListOpt => 38,
            NonTerminal::DeclList => 39,
            NonTerminal::DeclListPrime => 40,
            NonTerminal::VarDecl => 41,
            NonTerminal::StmtListOpt => 42,
            NonTerminal::StmtList => 43,
            NonTerminal::StmtListPrime => 44,
            NonTerminal::Stmt => 45,
            NonTerminal::AssignStmt => 46,
            NonTerminal::ReturnStmt => 47,
            NonTerminal::PrintStmt => 48,
            NonTerminal::IfStmt => 49,
            NonTerminal::ElsePart => 50,
            NonTerminal::WhileStmt => 51,
            NonTerminal::Expr => 52,
            NonTerminal::RelExpr => 53,
            NonTerminal::RelExprPrime => 54,
            NonTerminal::RelOp => 55,
            NonTerminal::AddExpr => 56,
            NonTerminal::AddExprPrime => 57,
            NonTerminal::MulExpr => 58,
            NonTerminal::MulExprPrime => 59,
            NonTerminal::Factor => 60,
            NonTerminal::FactorTail => 61,
            NonTerminal::ArgListOpt => 62,
            NonTerminal::ArgList => 63,
            NonTerminal::ArgListPrime => 64,
            NonTerminal::Type => 65,
        }
    }
}
